App\Entity\Location:
  properties:
    longitude:
      - Range:
          min: -180
          max:  180
          groups: [new,edit]
    latitude:
      - Range:
          min: -90
          max:  90
          groups: [new,edit]

    city:
      - Regex:
          pattern: '/^[a-zA-Z]+$/'